name: HAMQTT Integration Workflow - { INTEGRATION_NAME }

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    tags: [ 'v*.*.*' ]
    paths:
      - HAMQTT.Integration.{ INTEGRATION_NAME }/**

jobs:
  build:
    uses: mavanmanen/HAMQTT/.github/workflows/hamqtt-integration-workflow.yml@main
    with:
      integration_name: { INTEGRATION_NAME }